### ISSUE TITLE
Version 1.18.0 is not published

### ISSUE THREAD

**Issue by limansky** [hseeberger/akka-http-json#175] opened 2017-09-29 14:18 UTC
Hi.

It looks like version 1.18.0 was not published to central. 
https://search.maven.org/#search|gav|1|g:"de.heikoseeberger"%20AND%20a:"akka-http-json4s_2.11"

**Comment by hseeberger** [comment] 2017-09-29 14:24
Duplicate of #172. Use 1.19.0-M2.

**Closed by hseeberger** 2017-09-29 14:24 UTC

**Comment by limansky** [comment] 2017-09-29 14:41
@hseeberger Is it stable enough, or I should prefer 1.17.0?

**Comment by hseeberger** [comment] 2017-09-29 14:50
It's using a circe milestone. The rest is stable.
