### ISSUE TITLE
Built-in content-types are disabled by akka-http-json4s

### ISSUE THREAD

**Issue by daniel-ac-martin** [hseeberger/akka-http-json#169] opened 2017-08-24 08:40 UTC
It seems that once a route has JSON support enabled with akka-http-json4s (and possibly with the alternatives too) it is no longer to POST to it with the standard content types, `application/x-www-form-urlencoded` and `multipart/form-data`, only `application/json` is allowed.

For example, the following route definition:

```scala
import akka.http.scaladsl.server.{ Directives, Route }

object TestRoutes extends Directives {
  def routes: Route =
    path("test") {
      formFields('name) { name =>
        complete(s"Hello $name")
      }
    }
}
```

can be posted to with cURL as follows:

```shell
$ curl -i -d 'name=foo' 'http://localhost/test'
HTTP/1.1 200 OK
Server: akka-http/10.0.9
Date: Thu, 24 Aug 2017 08:35:22 GMT
Content-Type: text/plain; charset=UTF-8
Content-Length: 9

Hello foo
```

But, once akka-http-json4s is introduced:

```scala
import akka.http.scaladsl.server.{ Directives, Route }
import de.heikoseeberger.akkahttpjson4s.Json4sSupport
import org.json4s.DefaultFormats
import org.json4s.native.Serialization

object TestRoutes extends Directives with Json4sSupport {
  implicit val formats = DefaultFormats
  implicit val serialization = Serialization

  def routes: Route =
    path("test") {
      formFields('name) { name =>
        complete(s"Hello $name")
      }
    }
}
```

we can no longer POST to it in the same way:

```shell
$ curl -i -d 'name=foo' 'http://localhost/test'
HTTP/1.1 415 Unsupported Media Type
Server: akka-http/10.0.9
Date: Thu, 24 Aug 2017 08:37:44 GMT
Content-Type: text/plain; charset=UTF-8
Content-Length: 71

The request's Content-Type is not supported. Expected:
application/json
```

Is this by design or necessity? It seems to me that ideally it would be best to be able to enable JSON support on a route without disabling any built-in functionality of akka-http.

**Comment by hseeberger** [comment] 2017-08-24 09:23
Duplicate of #148: please import the respective (un)marshallers in the smallest possible scopes (sub routes)

**Closed by hseeberger** 2017-08-24 09:23 UTC
